name: Checkout Composite Action
description: Checkout code from a repository
inputs:
  repository:
    description: Repository name
    required: true
  ref:
    description: The branch, tag or SHA to checkout
    required: false
    default: main
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
